# Generated by Django 4.1.4 on 2022-12-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=50, unique=True, verbose_name='ФИО')),
                ('age', models.PositiveIntegerField()),
                ('directions', models.CharField(max_length=50, verbose_name='Направления')),
                ('sex', models.CharField(max_length=50, verbose_name='Пол')),
                ('bthd', models.DateField(verbose_name='Дата рождения')),
                ('date_out', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
