# Generated by Django 4.1.4 on 2022-12-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='bthd',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
    ]
