# Generated by Django 4.1.4 on 2022-12-20 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_form', '0003_alter_categories_bthd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='bthd',
            field=models.DateTimeField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='date_out',
            field=models.DateTimeField(),
        ),
    ]
