# Generated by Django 4.1.4 on 2022-12-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint_form', '0005_alter_categories_date_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='date_out',
            field=models.DateField(auto_now_add=True),
        ),
    ]
